abbreviations = {
    'dutch':[
	{'match':'^Burgemeester\s+',	 'replace':'Burg. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Burg. Patijnlaan" = "Burgemeester Patijnlaan"'},
	{'match':'^Commandant\s+',	 'replace':'Cmdt. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Cmdt. Weynsstraat" = "Commandant Weynsstraat"'},
	{'match':'^doctor\s+',	 'replace':'dr ',	'concatenated':'no',	'separable':'yes'},
	{'match':'^Dokter\s+',	 'replace':'Dr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Dokter Crasbornplein" (? Is this correct ?)'},
	{'match':'^Dominee\s+',	 'replace':'ds ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Dominee Theodor Fliednerstraat"'},
	{'match':'^Gebroeders\s+',	 'replace':'Gebr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'[brothers] "Gebr. Blommestr." = "Gebroeders Blommestraat"'},
	{'match':'^Generaal\s+',	 'replace':'Gen. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Gen. Drubbelstr." = "Generaal Drubbelstraat"'},
	{'match':'^(.+\w)gracht$',	 'replace':'\1gr.',	'concatenated':'yes',	'separable':'yes' ,	'note':'[urban canal] "Herengr." = "Herengracht"'},
        {'match':'^Ingenieur\s+',	 'replace':'Ir. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Ir. Menneslaan" = "Ingenieur Menneslaan" = "ir Mennesln"'},
        {'match':'^Jonkheer\s+',	 'replace':'Jhr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Jhr. Marcus van Gerwenlaan"'},
        {'match':'^Kolonel\s+',	 'replace':'Kol. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Kol. Silvertopstraat" = "Kolonel Silvertopstraat"'},
        {'match':'^Kanunnik\s+',	 'replace':'Kan. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Kan. Peetersstr." = "Kanunnik Peetersstraat"'},
        {'match':'^Kardinaal\s+',	 'replace':'Kard. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Kard. Cardijnln." = "Kardinaal Cardijnlaan"'},
        {'match':'^Korte\s+',	 'replace':'Kte. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Kte. Winkelstraat" = "Korte Winkelstraat"'},
        {'match':'^Koning\s+',	 'replace':'Kon. ',	'concatenated':'no',	'separable':'yes' ,	'note':'[king] "Kon. Albertlaan" = "Koning Albertlaan"'},
        {'match':'^Koningin\s+',	 'replace':'Kon. ',	'concatenated':'no',	'separable':'yes' ,	'note':'[queen] "Kon. Beatrixplein" = "Koningin Beatrixplein"'},
        {'match':'^Laan\s+',	 'replace':'ln. ',	'concatenated':'yes',	'separable':'yes'},
        {'match':'^Lange\s+',	 'replace':'L. ',	'concatenated':'no',	'separable':'n/a' ,	'note':'"L. Leidsedwarsstraat" = "Lange Leidsedwarsstraat"'},
        {'match':'^Luitenant\s+',	 'replace':'Luit. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Luit. Lippenslaan" = "Luitenant Lippenslaan"'},
        {'match':'^(.+\w)markt$',	 'replace':'\1mkt.',	'concatenated':'yes',	'separable':'yes' ,	'note':'"Vrijdagmkt." = "Vrijdagmarkt"'},
        {'match':'^Meester\s+',	 'replace':'Mr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Mr. Richard Goossensstr." = "Meester Richard Goossensstraat"'},
        {'match':'^Mevrouw\s+',	 'replace':'Mevr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Mevr. Courtmansstr." = "Mevrouw Courtmansstraat"'},
        {'match':'^Monseigneur\s+',	 'replace':'Mgr ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Mgr. Nolensplein"'},
        {'match':'^Onze\-Lieve\-Vrouw(e)*\-',	 'replace':'O.L.V.-',	'concatenated':'yes',	'separable':'yes' ,	'note':'"O.L.V.-Waver" = "Onze-Lieve-Vrouw-Waver"'},
        {'match':'^Pastoor\s+',	 'replace':'Past. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Past. Wouterstr." = "Pastoor Wouterstraat"'},
        {'match':'^(.+\w)plein$',	 'replace':'\1pln.',	'concatenated':'yes',	'separable':'yes'},
        {'match':'^President\s+',	 'replace':'Pres. ',	'concatenated':'yes',	'separable':'yes' ,	'note':'Pres. Kennedylaan'},
        {'match':'^Prins\s+',	 'replace':'Pr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'[prince] "Prins Bernhardstraat"'},
        {'match':'^Prinses\s+',	 'replace':'Pr. ',	'concatenated':'no',	'separable':'yes' ,	'note':'[princess] "Prinses Beatrixlaan"'},
        {'match':'^Professor\s+',	 'replace':'Prof. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"Prof. Willemsstraat"'},
        {'match':'^(.+\w)straat$',	 'replace':'\1str.',	'concatenated':'yes',	'separable':'yes'},
        {'match':'^(.+\w)steenweg$',	 'replace':'\1stwg.',	'concatenated':'yes',	'separable':'yes' ,	'note':'"Grotestwg." = "Grotesteenweg"'},
	{'match':'^Sint\-\s+',	 'replace':'St. ',	'concatenated':'yes',	'separable':'yes' ,	'note':'"St. Paulusstr." = "St.-Paulusstr." = "Sint-Paulusstraat"'},
	{'match':'^Van\s+',      'replace':'V. ',       'concatenated':'no',    'separable':'yes' ,     'note':'"V. Gentstraat" = "Van Gentstraat"'},
	{'match':'^(.+\w) van (.+)$',	 'replace':'\1 v \2',	'concatenated':'no',	'separable':'yes' ,	'note':'"Jan v Gentstraat" = "Jan van Gentstraat"'},
	{'match':'^Van De\s+',	 'replace':'V. D. ',	'concatenated':'no',	'separable':'yes' ,	'note':'"V. D. Sweepstraat" = "Van De Sweepstraat" ="vd Sweepstr."'},
	{'match':'^(.+\w)vliet\s+',	 'replace':'\1vlt.',	'concatenated':'yes',	'separable':'yes' ,	'note':'"St.-Jansvlt." = "Sint-Jansvliet"'}
    ]
};
